# docker-compose stack for InfluxDB, InfluxDB Explorer e Grafana

# Adicione este arquivo em uma pasta em um diretório de sua escolha e execute o comando
# docker compose up -d

# Após instalaçao gere o token do Influxdb com o comando abaixo: 
# (o token é necessário para adicionar o Server do InfluxDB ao Explorer para visualizaçao de seus dados)
# docker compose exec influxdb3-core influxdb3 create token --admin

# Caso queira criar um novo bucket via postman segue um exemplo:
# POST - http://localhost:8181/api/v3/configure/database
# Bearer token criado deve ser informado 
# No Body
# {
#   "db": "telemetriabd",
#   "retention_period": "1y"
# }

services:
  influxdb3-core:
    image: influxdb:3-core
    container_name: influxdb3-core
    command:
      - influxdb3
      - serve
      - --object-store=file
      - --data-dir=/var/lib/influxdb3/data
      - --node-id=node0
      - --http-bind=0.0.0.0:8181
    ports:
      - "8181:8181"
    volumes:
      - ./influxdb3-data:/var/lib/influxdb3/data
    environment:
      - TZ=America/Sao_Paulo
    restart: unless-stopped
    networks: [influx-net]
    healthcheck:
      test: ["CMD", "sh", "-c", "nc -z localhost 8181"]
      interval: 10s
      timeout: 3s
      retries: 10

  explorer:
    image: influxdata/influxdb3-ui:1.3.0
    container_name: influxdb3-explorer
    ports:
      - "8888:80"
    volumes:
      - ./db:/db:rw
    restart: unless-stopped
    depends_on:
      influxdb3-core:
        condition: service_healthy
    networks: [influx-net]

  grafana:
    image: grafana/grafana:11.2.2
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      # opcional: trava criação de usuários por convite/autoregistro
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./grafana-data:/var/lib/grafana
    restart: unless-stopped
    depends_on:
      influxdb3-core:
        condition: service_healthy
    networks: [influx-net]

networks:
  influx-net:
    driver: bridge



